#.gitlub-ci.yml
stages:
  - test
  - delievery
  - deploy
  
test-job:
  stage: test
  script:
    - docker compose -f docker/test/docker-compose.yml down				# Убиваем возможный докер контейнер
    - docker compose -f docker/test/docker-compose.yml build project			# Принудительно билдим наш образ 
    - docker compose -f docker/test/docker-compose.yml up --abort-on-container-exit	# Когда manage.py test выполнится, то наш youtube завершит
    											  работу, а заодно и БД благодаря флагу
    											  
delievery-job:
  stage: delievery
  only:
    - main						# Будет срабатывать, только после merge в главную ветку. И пушит туда новый образ
  script:
    - docker login -p $DOCKER_REGISTRY_KEY -u $DOCKER_REGISTRY_USER registry.soaqa.ru
    - docker tag yt_django:test $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE

deploy-job: # Качаем новую версию образа: docker-compose pull project --> docker compose up | Ручное CD
  stage: deploy
  when: manual
  only:
    - main
  script:
    - ssh server deploy.sh								# Автоматический CD
    
											# CD используя Watchtower. В docker-compose.yml
watchtower:
  image: containrrr/watchrower
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /root/.docker/config.json:/config.json
  command: --interval 30 yt_django