version: "3.5"        # Версия Docker Compose
services: 						# Описание работы всех контейнеров (т.е. сервис - один контейнер)
  web-server
    image: nginx:stable
    container_name: mynginx
    volumes:
      - "/opt/web/html:/var/www/html"
      - "/opt/web/pics:/var/www/pictures"
      - "nginx-config:/var/www/config"
    environment:
      - "NGINX_HOST=web.tdotv.de"
      - "NGINX_PORT=80"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped # always/no/on-failure
volumes:
  nginx-config:
networks:
  default:
    driver: bridge
    name: webnet

docker compose up (-d)